Assistant checkpoint: Fix Task1 to handle uppercase letters correctly
Assistant generated file changes:
- src/test/java/tractor/Task1.java: Fix Task1 to handle uppercase letters correctly

---

User prompt:

Running the code in my project results in the following:

```
: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running ToAnyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running algo.FindOrderStatisticTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running ABCStringTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec

Results :

Failed tests:   testTask1(tractor.TasksTest): expected:<[]> but was:<[A]>

Tests run: 82, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.213 s
[INFO] Finished at: 2025-01-24T22:17:17Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project java_problems: There are test failures.
[ERROR]
[ERROR] Please refer to /home/runner/workspace/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

If applicable, propose a fix immediately.